version: '3.8'

services:
 concerto:
  build:
   context: .
  ports:
   - 80:80
   - 443:443
   #
   # Uncomment the below 5 lines to run tests through the
   # Fiddler proxy
   #
   - 8888:8888
   - 9229:9229
  environment:
   http_proxy: "http://host.docker.internal:8888/"
   https_proxy: "http://host.docker.internal:8888/"
  volumes:
   - ./:/app
   - test_data:/results
   #
   # Attempting to run the performance tests through Fiddler
   # results in invalid certificate error:
   # x509: certificate signed by unknown authority
   # However, running the Axios functional tests is fine
   #
  #command: /bin/sh -c "npm run test ; npm run perf-test"
  #command: npm run test
  command: npm run perf-test

volumes:
 test_data: