
name: Copy .gitignore to gitignore

on: 
  push:
    branches: [ "develop" ]

jobs:
  build:
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Copy file 
        run: cp .gitignore gitignore

      - name: commit
        run: |
          git config --local user.email "anamika.bassi@fonterra.com"
          git config --local user.name "ZEUS\bassiana"
          git add gitignore
          git diff --quiet && git diff --staged --quiet || git commit -m "Added gitignore file"
          git push
