
name: Copy .gitignore to gitignore

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Copy file 
        run: cp .gitignore gitignore

      - name: commit
        run: |
          git config --local user.email "anamika.bassi@fonterra.com"
          git config --local user.name "ZEUS\bassiana"
          git add gitignore
          git commit -m "added gitignore file"
          git push
